name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/hello-world-docker-action@9a36e3c710049d8e8b8afbfa376affbc4cfdb6ca
      with:
        who-to-greet: 'actions-packages-examples'
